# Generated by Django 4.2.4 on 2023-09-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarize', '0003_rename_user_id_prompts_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompts',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='prompts',
            name='patient_id',
            field=models.IntegerField(default=7273),
        ),
    ]
